apiVersion: apps/v1
kind: Deployment
metadata:
  name:  workout-manager
  namespace: default
  labels:
    app:  workout
    svc: manager
spec:
  selector:
    matchLabels:
      app:  workout
      svc: manager
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  workout
        svc: manager
    spec:
      containers:
      - name:  workout-manager
        image:  andrewlm/workouts:0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
      envFrom:
      - configMapRef: 
          name: workout-config
      restartPolicy: Always
      
    
