version: 2.1
orbs:
  golangci-lint: timakin/golangci-lint@volatile
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.18.3
        auth:
          username: andrewlm
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v0-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v0-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: 
          name: Run service with default envs
          command: make
          background: true
      - run:
          name: Run tests
          command: go test -v $(go list ./... | circleci tests split)
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: 
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_IMAGE:latest .
            docker tag  $DOCKER_IMAGE:latest $DOCKER_IMAGE:0.1
            docker tag  $DOCKER_IMAGE:latest $DOCKER_IMAGE:0.1.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:0.1
            docker push $DOCKER_IMAGE:0.1.$CIRCLE_BUILD_NUM
workflows:
  build:
    jobs:
      - golangci-lint/lint
      - build

      # TODO: add ssh-key with read/write permission
      # - run:
      #     name: Tagged git repository
      #     command: |
      #       git tag -f v0.1-release
      #       git push origin v0.1-release --force
