version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.18.3
        auth:
          username: andrewlm
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v0-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v0-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: 
          name: Run service with default envs
          command: make
          background: true
      - run:
          name: Run tests
          command: go test -v $(go list ./... | circleci tests split)

