apiVersion: apps/v1
kind: Deployment
metadata:
  name:  muscle-manager
  namespace: default
  labels:
    app:  muscle
    svc: manager
spec:
  selector:
    matchLabels:
      app:  muscle
      svc: manager
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  muscle
        svc: manager
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  muscle-manager
        image:  andrewlm/workouts:0.1.12
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
      restartPolicy: Always
